// <auto-generated />
using System;
using App.CheckIn.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace App.CheckIn.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppCheckInDbContext))]
    [Migration("20190517184430_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("App.CheckIn.Domain.EventSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("EnablePushNotification");

                    b.Property<string>("EventCode");

                    b.Property<string>("EventDescription");

                    b.Property<TimeSpan>("EventDuration");

                    b.Property<string>("EventName");

                    b.Property<string>("EventRoom");

                    b.Property<DateTimeOffset>("EventStartTime");

                    b.Property<bool>("Notified");

                    b.Property<string>("UserEmail");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
